import type { LectureMetadata } from '@/types';
import { SCHEDULING_SUBTOPICS } from './lectureSubtopics';

// רישום מרכזי של כל ההרצאות בקורס - 10 הרצאות לפי הסילבוס הרשמי.
// כל עוד isReady === false - תוצג קומפוננטת EmptyLecture במקום התוכן.
export const LECTURES: LectureMetadata[] = [
  {
    id: 'introduction',
    number: 1,
    title: 'מבוא למערכות הפעלה',
    englishTitle: 'Introduction to Operating Systems',
    description:
      'סקירה כללית של מערכות הפעלה - מהן, מה הן עושות, וכיצד הן בנויות. הרצאת פתיחה שמציגה את המבנה של מחשב, interrupts, היררכיית זיכרון, ומערכות מרובות מעבדים.',
    estimatedMinutes: 60,
    topics: [
      'מהי מערכת הפעלה ומה תפקידיה',
      'מבנה מחשב: Hardware, OS, Applications, Users',
      'אתחול מחשב (Bootstrap) ו-Firmware',
      'ארגון מערכת מחשב ו-Bus',
      'Interrupts - המנגנון המרכזי של OS',
      'I/O סינכרוני מול אסינכרוני',
      'היררכיית התקני אחסון',
      'Direct Memory Access (DMA)',
      'מערכות מרובות מעבדים (Multiprocessing)',
      'Multiprogramming ו-Timesharing',
    ],
    isReady: true,
  },
  {
    id: 'os-structures',
    number: 2,
    title: 'מבני מערכות הפעלה',
    englishTitle: 'Operating-System Structures',
    description:
      'שירותי OS, ממשקי משתמש, System Calls ו-APIs, Dual-Mode, System Programs, ומבני OS שונים - Simple, Monolithic, Layered, Microkernel, Modular ו-Hybrid.',
    estimatedMinutes: 60,
    topics: [
      'שירותי מערכת הפעלה',
      'ממשקי משתמש (CLI, GUI, Touch)',
      'Dual-Mode Operation',
      'System Calls ו-APIs',
      'העברת פרמטרים',
      'System Programs',
      'Policy vs Mechanism',
      'מבני OS (Simple, Monolithic, Layered, Microkernel, Modular, Hybrid)',
      'Virtual Machines',
      'Debugging & Performance Tuning',
    ],
    isReady: true,
  },
  {
    id: 'processes',
    number: 3,
    title: 'תהליכים',
    englishTitle: 'Processes',
    description:
      'מהו תהליך, איך הוא מאוחסן בזיכרון, חמשת מצבי התהליך, ה-PCB, Context Switch, תורים ומתזמנים, יצירה וסיום תהליכים ב-UNIX, ו-IPC בסיסי.',
    estimatedMinutes: 75,
    topics: [
      'תוכנית מול תהליך (Program vs Process)',
      'מבנה זיכרון של תהליך: Text, Data, Heap, Stack',
      '5 מצבים: New / Ready / Running / Waiting / Terminated',
      'Process Control Block (PCB)',
      'Context Switch ועלותו',
      'תורי תהליכים: Job / Ready / Device',
      'מתזמנים: Short / Long / Medium-term',
      'CPU-bound מול I/O-bound',
      'יצירת תהליכים: fork, exec, wait, exit',
      'Zombie, Orphan, Cascading Termination',
      'IPC: Shared Memory מול Message Passing',
    ],
    isReady: true,
  },
  {
    id: 'scheduling',
    number: 4,
    title: 'תזמון מעבד',
    englishTitle: 'CPU Scheduling',
    description:
      'בחירת התהליך הבא שירוץ על ה-CPU: מחזורי CPU/I/O, Scheduler ו-Dispatcher, מדדי תזמון, והיכרות ראשונית עם FCFS, SJF, SRTF, Priority, Round Robin ותורים מרובי רמות.',
    estimatedMinutes: 70,
    topics: [
      'מחזור CPU burst ו-I/O burst',
      'נקודות החלטה של ה-Scheduler',
      'Dispatcher ו-dispatch latency',
      'מדדי תזמון: CPU utilization, throughput, turnaround, waiting, response',
      'FCFS',
      'SJF ו-SRTF',
      'Priority Scheduling',
      'Round Robin ו-quantum',
      'Multilevel Queue ו-Multilevel Feedback Queue',
      'נושאים משלימים: burst prediction, multiprocessor, real-time, threads, OS examples, evaluation',
    ],
    subtopics: SCHEDULING_SUBTOPICS,
    isReady: true,
  },
  {
    id: 'synchronization',
    number: 5,
    title: 'סנכרון ו-Semaphores',
    englishTitle: 'Synchronization and Semaphores',
    description: '',
    estimatedMinutes: null,
    topics: [],
    isReady: false,
  },
  {
    id: 'deadlocks',
    number: 6,
    title: 'Deadlocks',
    englishTitle: 'Deadlocks',
    description: '',
    estimatedMinutes: null,
    topics: [],
    isReady: false,
  },
  {
    id: 'memory',
    number: 7,
    title: 'ניהול זיכרון',
    englishTitle: 'Memory Management',
    description: '',
    estimatedMinutes: null,
    topics: [],
    isReady: false,
  },
  {
    id: 'virtual-memory',
    number: 8,
    title: 'זיכרון וירטואלי ו-Paging',
    englishTitle: 'Virtual Memory and Paging',
    description: '',
    estimatedMinutes: null,
    topics: [],
    isReady: false,
  },
  {
    id: 'filesystem',
    number: 9,
    title: 'מערכות קבצים - ממשק',
    englishTitle: 'File Systems - Interface',
    description: '',
    estimatedMinutes: null,
    topics: [],
    isReady: false,
  },
  {
    id: 'filesystem-impl',
    number: 10,
    title: 'מערכות קבצים - מימוש',
    englishTitle: 'File Systems - Implementation',
    description: '',
    estimatedMinutes: null,
    topics: [],
    isReady: false,
  },
];

export function getLectureById(id: string): LectureMetadata | undefined {
  return LECTURES.find((lecture) => lecture.id === id);
}
