import type { LectureSubtopic } from '@/types';

export const SYNCHRONIZATION_SUBTOPICS: LectureSubtopic[] = [
  {
    id: 'overview',
    title: 'פתיחה',
    englishTitle: 'Overview',
    description: 'הבעיה שסנכרון בא לפתור ומפת הנושאים.',
    group: 'foundation',
  },
  {
    id: 'critical-section',
    title: 'בעיית Critical Section',
    englishTitle: 'Critical Section Problem',
    description: 'הגדרת הבעיה, שלושת התנאים, ו-Race Condition.',
    group: 'foundation',
  },
  {
    id: 'peterson',
    title: 'פתרון Peterson',
    englishTitle: "Peterson's Solution",
    description: 'פתרון תוכנתי לשני תהליכים עם turn ו-flag.',
    group: 'foundation',
  },
  {
    id: 'hardware',
    title: 'סנכרון חומרה',
    englishTitle: 'Synchronization Hardware',
    description: 'פעולות אטומיות: TestAndSet ו-Swap.',
    group: 'foundation',
  },
  {
    id: 'semaphores',
    title: 'Semaphores',
    englishTitle: 'Semaphores',
    description: 'wait() ו-signal(), binary ו-counting, תור חסימה.',
    group: 'core',
  },
  {
    id: 'classic-problems',
    title: 'בעיות קלאסיות',
    englishTitle: 'Classic Synchronization Problems',
    description: 'שלוש בעיות קלאסיות שמדגימות אתגרי סנכרון.',
    group: 'classic',
  },
  {
    id: 'bounded-buffer',
    title: 'Bounded Buffer',
    englishTitle: 'Bounded Buffer Problem',
    description: 'מפיק-צרכן עם חוצץ מוגבל.',
    group: 'classic',
  },
  {
    id: 'readers-writers',
    title: 'Readers-Writers',
    englishTitle: 'Readers-Writers Problem',
    description: 'קוראים מרובים מול כותב בלעדי.',
    group: 'classic',
  },
  {
    id: 'dining-philosophers',
    title: 'Dining Philosophers',
    englishTitle: 'Dining Philosophers Problem',
    description: 'deadlock ורעב — פילוסופים שמחכים לצלחות.',
    group: 'classic',
  },
  {
    id: 'monitors',
    title: 'Monitors',
    englishTitle: 'Monitors',
    description: 'מבנה ברמה גבוהה שמפשט סנכרון ומקטין טעויות.',
    group: 'advanced',
  },
  {
    id: 'practice',
    title: 'תרגול',
    englishTitle: 'Practice',
    description: '10 שאלות אמריקאיות קצרות לתרגול לפני מבחן.',
    group: 'practice',
  },
];

export const SCHEDULING_SUBTOPICS: LectureSubtopic[] = [
  {
    id: 'overview',
    title: 'פתיחה',
    englishTitle: 'Overview',
    description: 'כניסה קצרה להרצאה ומפת הנושאים.',
    group: 'foundation',
  },
  {
    id: 'basic-concepts',
    title: 'מושגי בסיס',
    englishTitle: 'Basic Concepts',
    description: 'multiprogramming, מחזור CPU/I/O והתפלגות bursts.',
    group: 'foundation',
  },
  {
    id: 'scheduler-dispatcher',
    title: 'Scheduler ו-Dispatcher',
    englishTitle: 'Scheduler and Dispatcher',
    description: 'נקודות החלטה, preemption, ותפקיד ה-Dispatcher.',
    group: 'foundation',
  },
  {
    id: 'criteria',
    title: 'מדדי תזמון',
    englishTitle: 'Scheduling Criteria',
    description: 'CPU utilization, throughput, turnaround, waiting ו-response.',
    group: 'foundation',
  },
  {
    id: 'fcfs',
    title: 'FCFS',
    englishTitle: 'First-Come, First-Served',
    description: 'סדר הגעה, nonpreemptive ו-convoy effect.',
    group: 'algorithms',
  },
  {
    id: 'sjf',
    title: 'SJF',
    englishTitle: 'Shortest Job First',
    description: 'בחירת ה-burst הקצר ביותר בגרסה nonpreemptive.',
    group: 'algorithms',
  },
  {
    id: 'burst-prediction',
    title: 'חיזוי CPU burst',
    englishTitle: 'CPU Burst Prediction',
    description: 'הקושי המעשי של SJF ו-exponential averaging.',
    group: 'algorithms',
  },
  {
    id: 'srtf',
    title: 'SRTF',
    englishTitle: 'Shortest Remaining Time First',
    description: 'SJF preemptive לפי הזמן שנותר.',
    group: 'algorithms',
  },
  {
    id: 'priority',
    title: 'Priority Scheduling',
    englishTitle: 'Priority Scheduling',
    description: 'עדיפויות, starvation, aging ו-SJF כמקרה פרטי.',
    group: 'algorithms',
  },
  {
    id: 'round-robin',
    title: 'Round Robin',
    englishTitle: 'Round Robin',
    description: 'שלד הנושא לגל הבא.',
    group: 'later',
  },
  {
    id: 'io-round-robin',
    title: 'Round Robin עם I/O',
    englishTitle: 'Round Robin with I/O',
    description: 'תהליכים עם שלבי CPU ו-I/O — מחזור חיים מלא עם ציר זמן.',
    group: 'later',
  },
  {
    id: 'multilevel-queue',
    title: 'Multilevel Queue',
    englishTitle: 'Multilevel Queue',
    description: 'שלד תורים מרובי רמות.',
    group: 'later',
  },
  {
    id: 'multilevel-feedback-queue',
    title: 'Multilevel Feedback Queue',
    englishTitle: 'Multilevel Feedback Queue',
    description: 'שלד תורים מרובי רמות עם משוב.',
    group: 'later',
  },
  {
    id: 'secondary-topics',
    title: 'נושאים משלימים',
    englishTitle: 'Secondary Topics',
    description: 'נושאי המשך קצרים מהשקפים.',
    group: 'wrapup',
  },
  {
    id: 'practice',
    title: 'תרגול',
    englishTitle: 'Practice',
    description: 'חשיבה לקראת שאלות מבחן.',
    group: 'wrapup',
  },
  {
    id: 'summary',
    title: 'סיכום',
    englishTitle: 'Summary',
    description: 'נקודות לזכור וסגירת ההרצאה.',
    group: 'wrapup',
  },
];
